version: '2'

services:
  base:
    image: golang:1.6
    volumes:
      - "$HOME/.aws:/root/.aws"
      - ".:/usr/src/myapp"
    working_dir: /usr/src/myapp

  build:
    extends:
      service: base
    environment:
      GOOS: linux
      GOARCH: amd64
    command: make build

  deploy:
    extends:
      service: base
    environment:
      AWS_REGION: ap-southeast-2
    command: make run
