version: '2'

services:
  base:
    image: golang:1.6
    volumes:
      - "$HOME/.aws:/root/.aws"
      - ".:/usr/src/myapp"
    working_dir: /usr/src/myapp

  data_volume:
    image: debian:wheezy
    volumes:
      - /go

  build:
    extends:
      service: base
    volumes_from:
      - data_volume
    environment:
      GOOS: linux
      GOARCH: amd64
    command: make build

  run:
    extends:
      service: base
    environment:
      AWS_REGION: ap-southeast-2
    command: make run
