Description: >
  This template is only a Test. You can safely Delete Me

Parameters:

  VpcID:
    Description: The ID of the VPC
    Type: String

  InPort:
    Description: The Ingress Port Number to Add
    Type: String

  OutPort:
    Description: The Egress Port Number to Add
    Type: String

Resources:

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId:
        Ref: VpcID
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: !Ref InPort
        ToPort: !Ref InPort
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: !Ref OutPort
        ToPort: !Ref OutPort
        CidrIp: 0.0.0.0/0

Outputs:

  SecurityGroupID:
    Description: A Security Group ID
    Value: !Ref InstanceSecurityGroup
