Description: >
  This template creates a VPC, with a 3 Subnet Types
  (Public, App and Data) across 3 Availability Zones.

Parameters:

  EnvironmentName:
    Description: The name to associate rescoures with
    Type: String

  VpcCIDR:
    Description: Please enter the IP CIDR range
    Type: String

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-vpc

Outputs:

  VPC:
    Description: A reference to the created VPC
    Value: !Ref VPC
